void add_endpoint(unsigned int *, int *, unsigned int, unsigned int);
void interval_operation(int, int, unsigned int, int, int, int, int, unsigned int *, int *, struct level2 *, int);
int rule_check(int *, int *, int, int, int);
int count_bit(int);
int log_2(int);
void layer_count(int, int *);
int rule_check_exact(int *, int *, int, int);
int rule_check_cover(int *, int *, int, int);
int rule_check_merge(int *, int *, int, int, int);
int cmp_r(const void *, const void *);
int ceil_log2(unsigned long long);